services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/app
    depends_on:
      - mysql
      - php
    networks:
      - evollt
  php:
    build:
      context: docker
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/app
    networks:
      - evollt
  mysql:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - docker/.env
    volumes:
      - "./docker/volume/mysql:/var/lib/mysql"
    networks:
      - evollt
  composer:
    build:
      context: docker
      dockerfile: composer.Dockerfile
    volumes:
      - ./:/var/www/app
    networks:
      - evollt
  artisan:
    build:
      context: docker
      dockerfile: php.Dockerfile
    volumes:
      - ./:/var/www/app
    entrypoint: ["php", "/var/www/app/artisan"]
    networks:
      - evollt
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    env_file:
      - docker/.env
    networks:
      - evollt
networks:
  evollt:
    external: true
    name: ${DOCKER_NETWORK}
