name: Evollt Academy PROD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Установка SSH-клиента для подключения к серверу
      - name: Installing SSH client
        run: sudo apt-get install -y openssh-client

      - name: Set NGINX_PORT based on branch
        run: echo "NGINX_PORT=8001" >> $GITHUB_ENV

      - name: Generate docker-compose.yml
        run: |
          envsubst < docker-compose.template.yml > docker-compose.yml

      # Добавляем SSH-ключ
      - name: Add SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          eval $(ssh-agent -s)
          ssh-add private_key

      - name: Deploy application via SSH
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} <<EOF
          # Вход в Docker Hub на сервере
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

          # Клонируем или обновляем репозиторий
          if [ ! -d "/var/www/prod/backend" ]; then
            git clone git@github.com:Evollt-Project/Backend.git /var/www/prod/backend
          else
            cd /var/www/prod/backend
            git reset --hard
            git pull origin master
          fi

          # Переход в директорию проекта
          cd /var/www/prod/backend

          # Остановка и удаление старых контейнеров
          docker compose down

          # Запуск новых контейнеров
          docker compose up -d --build
          docker compose run composer install
          EOF
